### ISSUE TITLE
There was translation mistake in [help] string, please change

### ISSUE THREAD

**Issue by abusarimhindi** [backmeupplz/IsBotDownBot#3]
https://github.com/backmeupplz/IsBotDownBot/blob/6b5c421f2493acc3e735ca6157b5d47894f507ac/locales/ur.yaml#L3

Correct translation:

میں جانچ کر بتا سکتا ہوں کہ کوئی بوٹ غیر فعال ہےیا نہیں۔ بس مجھے آپ بوٹ کی آئی ڈی ارسال کریں جیسے کہ @IsBotDownBot اور میں جانچ کر بتاؤں گا کہ یہ فعال ہے کہ نہیں۔ اگر آپ کسی بوٹ کی سبسکرپشن کو ختم کرنا چاہتے ہیں تو مجھے /delete کا کمانڈ بھیجیں۔زبان بدلنے کے لیے /language کمانڈ استعمال کریں۔ تعاون: @borodutch_support۔

**Comment by abusarimhindi** [comment]
Please edit this. Thank you

**Comment by backmeupplz** [comment]
@abusarimhindi Can you check if it's fixed now, please?

**Comment by abusarimhindi** [comment]
> @abusarimhindi Can you check if it's fixed now, please?

Now it is ok.
